### PR TITLE
Spring Security: JWT Authentication and Authorization 

### PR DESCRIPTION
**Pull request by bijay-shrestha**
This contains Shelly's dream of having User and UserRole.
It also contains a full-fledged implementation of JWT Authentication and Authorization.

### CODE REVIEW

**Review by shellyneira — COMMENTED** [review]
Dear void! What a long PR!!!!! 🤨 lol

**Comment by bijay-shrestha** [comment]
Yes Ms. Basssssssstoooosssss!

**Review by shellyneira — APPROVED** [review]
Mannnnnnnnnnn. Ill approve just because we only have 2 days lasts to show this project. =l

**Comment by bijay-shrestha** [comment]
> Mannnnnnnnnnn. Ill approve just because we only have 2 days lasts to show this project. =l

Laaaatssssss do it!

**Pull request merged**
